name: Build & Push Docker Image

on:
  push:
    branches:
      - main # O 'master'

env:
  DOCKER_HUB_USERNAME: ilyyessy # Reemplaza con tu nombre de usuario de Docker Hub
  IMAGE_NAME: mi-app-sencilla
  IMAGE_TAG: 1.0

jobs:
  build-test-and-push: # Cambiamos el nombre del job para reflejar los nuevos pasos
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18' # Asegúrate de que coincida con la versión en tu Dockerfile

    - name: Install dependencies
      run: npm install

    - name: Run unit tests and collect coverage
      run: npm test -- --coverage # Ejecuta Jest con cobertura de código

    # Aquí podríamos añadir un paso para subir el reporte de cobertura a un servicio si fuera necesario.
    # Por ahora, la cobertura se mostrará en los logs.

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ env.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
        cache-from: type=gha,scope=${{ github.workflow }}
        cache-to: type=gha,mode=max,scope=${{ github.workflow }}